# Generated by Django 5.1.6 on 2025-03-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcana', '0002_subheader_code_alter_subheader_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
