# Generated by Django 5.1.6 on 2025-03-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcana', '0003_language_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
